name: Test and Prebuild
on: [push]
jobs:
  build-alpine-arm64:
    runs-on: ubuntu-18.04
    container: node:17
    steps:
      - run: apt-get update
      - run: apt-get -y install build-essential python
      - uses: nao20010128nao/musl-cross-compilers@v0.5
        with:
          target: aarch64-linux-musl
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 17
      - run: npm install
      - run: npm run prebuild-arm64
        env:
          CC: aarch64-linux-musl-gcc
          CXX: aarch64-linux-musl-g++
      - run: tar --create --verbose --file=prebuild-linux-arm64.tar -C prebuilds .
      - name: Prebuild
        uses: softprops/action-gh-release@v1
        with:
          files: prebuild-alpine-arm64.tar
